### ISSUE TITLE
No messages arriving - how to debug?

### ISSUE THREAD

**Issue by solars** [jschniper/gelf_logger#19]
Hi there,

I have Graylog running and verified it's receiving via an echo/nc line.
However, I don't receive any log statements out of my application.

I used the exact config as per Readme - how could I debug what the problem is?

**Comment by jschniper** [comment]
If you run `netcat -l -u localhost 12201` and change the config to point to 127.0.0.1, you should see the messages in netcat.

If I had to guess wildly, it might be because of mismatch on the timezones. For example, if your graylog server is running in UTC and the application is in EST or something along those lines. Check out the utc_log flag in https://hexdocs.pm/logger/Logger.html#module-runtime-configuration

**Comment by solars** [comment]
@jschniper you were right - I even had this line in my config but in the wrong environment :/
Thanks a lot!
